### ISSUE TITLE
Part 4 : typo + question fig 12

### ISSUE THREAD

**Issue by mpjoubertdebellefon** [ThomasFaria/retex-innovation-insee#32]
just a typo > Using a MLflow model _registry_ enables to integrate the pre-processing step before each prediction to the API

Fig 12 is not very clear to me : why is'nt there a line from the container registry to the operator, in order to represent the part "any change in the application manifests is directly propagated to the deployment on the cluster" ? And does the fact that the line from the container registry to the orchestrator is dotted means something, eg. a manual action ? The place of the operator  is not obvious to me in this drawing.

**Comment by avouacr** [comment]
First remark : it was not a typo but it was not clear either, I reformulated

Second remark : it's because of what I tried to explain in the paragraph just above, but maybe it wasn't clear enough. We could deploy directly the built image on Kubernetes with custom manifests - hence the dotted line - but it's not the best approach for reasons desctibed in the paragraph. Thus, we use a GitOps repo with the manifests, and the operator is in charge of tracking any change happening there. When it detects a change - notably, a change in the tag of the docker image to be deployed - it modifies the manifests on the Kubernetes cluster, and it is Kubernetes that fetches and deploys the last image. There is no direct link between the operator and the container registry.
